openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: YouTube Data API v3
  description: >-
    The YouTube Data API v3 is an API that provides access to YouTube data, such
    as videos, playlists, and channels.
  version: v3
  x-discovery-doc-revision: '20230103'
  x-generated-date: '2023-01-05'
externalDocs: {}
servers: []
components: {}
paths: {}
